#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server:

# Check if correct number of arguments are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer the file using scp with strict host key checking disabled
scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "$username@$server_ip":~/
