#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

# Define the content of the custom 404 page
NOT_FOUND_PAGE="<html>\n<head><title>404 Not Found</title></head>\n<body><h1>404 Not Found</h1><p>Ceci n'est pas une page</p></body>\n</html>"

# Install Nginx
apt-get update -y
apt-get install nginx -y

# Configure Nginx to use the custom 404 page
echo -e "$NOT_FOUND_PAGE" > /usr/share/nginx/html/404.html
sed -i '/^}/i error_page 404 /404.html;' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
