#!/usr/bin/env bash
# a setup script for configuring Nginx with custom settings

# Update package repositories
apt-get -y update
# Install Nginx
apt-get -y install nginx
ufw allow 'Nginx HTTP'

# Define paths and content
INDEX_FILE="/var/www/html/index.nginx-debian.html"
CUSTOM_404_FILE="/usr/share/nginx/html/custom_404.html"
NGINX_CONF="/etc/nginx/nginx.conf"
NGINX_DEFAULT_CONF="/etc/nginx/sites-available/default"
NGINX_SITES_ENABLED="/etc/nginx/sites-enabled"

INDEX_CONTENT="Hello World!"
CUSTOM_404_CONTENT="Ceci n'est pas une page"
NGINX_CONFIG_APPEND="
    rewrite ^\/redirect_me https:\/\/github.com\/Isaac-Ndirangu-Muturi-749 permanent;

    error_page 404 \/custom_404.html;
    location = \/custom_404.html {
        root \/usr\/share\/nginx\/html;
        internal;
    }
"

# Create default index file
echo "$INDEX_CONTENT" > "$INDEX_FILE"
# Create custom 404 page
echo "$CUSTOM_404_CONTENT" > "$CUSTOM_404_FILE"

# Configure Nginx
X_SERVED_BY_HEADER="X-Served-By \"$HOSTNAME\";"
sed -i "/server_name _;/a $NGINX_CONFIG_APPEND" "$NGINX_DEFAULT_CONF"
sed -i "s/include $NGINX_SITES_ENABLED\/\*;/include $NGINX_SITES_ENABLED\/\*;\n\tadd_header $X_SERVED_BY_HEADER/" "$NGINX_CONF"

# Restart Nginx to apply changes
service nginx restart
