#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

sudo apt-get update
# Install nginx and automatically answer "yes" to all prompts.
sudo apt-get -y install nginx
sudo service nginx start

# Add a custom header to nginx configuration file to identify the server.
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
# Explanation:
# - `sudo`: Executes the command with superuser privileges.
# - `sed`: Stream editor for filtering and transforming text.
# - `-i`: Edit files in place.
# - `"11i\\\tadd_header X-Served-By $HOSTNAME;"`: Inserts a new line before line 11 in the nginx configuration file.
#   - `11i`: Insert before line 11.
#   - `\\\t`: Inserts a tab character before the header.
#   - `add_header X-Served-By $HOSTNAME;`: Adds the custom header with the server hostname.

# Write "Hello World!" to the default nginx index file.
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
