#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

# Update package list and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create index page
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Define variable for Nginx configuration file
NGINX_CONF="/etc/nginx/sites-available/default"

sudo tee -a "$NGINX_CONF" >/dev/null <<EOF

server {
   listen 80 default_server;
   listen [::]:80 default_server;

   root /var/www/html;
   index index.html;

   # Add custom header
   add_header X-Served-By \$hostname;

   # Add redirect for /redirect_me
   location /redirect_me {
      return 301 https://github.com/Isaac-Ndirangu-Muturi-749;
   }

   # Add custom error page redirection
   error_page 404 /custom_404.html;
   location = /custom_404.html {
      root /usr/share/nginx/html;
      internal;
   }
}

EOF

# Start Nginx service
sudo service nginx start
