#!/usr/bin/env bash
# Installs and sets up HAProxy

set -e  # Exit immediately if a command exits with a non-zero status

# Update package lists and upgrade installed packages
sudo apt-get update
sudo apt-get -y upgrade

# Install HAProxy
sudo apt-get -y install haproxy

# Enable HAProxy by modifying the configuration file
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Backup the original configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

# Append configuration for the HAProxy load balancer
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF
listen 339243-lb-01
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 339243-web-02 35.153.193.23:80 check
    server 339243-web-01 100.27.4.237:80 check
EOF

# Start HAProxy service
sudo service haproxy start

echo "HAProxy setup completed successfully."
