#!/usr/bin/env bash
# Bash script to ping an IP address

# Check if an argument is provided
if [ "$#" -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
else

fi

# Extract the IP address from the argument
ip_address=$1

# Ping the IP address 5 times and display the results
ping -c 5 "$ip_address"
