#!/usr/bin/env bash
# This script displays numbers and provides messages based on specific iterations

# Initialize a counter
counter=1

# Use a while loop to iterate from 1 to 20
while [ $counter -le 20 ]; do
    # Use the case statement to display messages for specific iterations
    case $counter in
        4)
            echo $counter
            echo "bad luck from China"
            ;;
        9)
            echo $counter
            echo "bad luck from Japan"
            ;;
        17)
            echo $counter
            echo "bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac

    ((counter++))
done
