#!/usr/bin/env bash

file_path="school"

# Check if the file exists
if [ -e "$file_path" ]; then
    echo "school file exists"

    # Check if the file is empty
    if [ -s "$file_path" ]; then
        echo "school file is not empty"

        # Check if the file is a regular file
        if [ -f "$file_path" ]; then
            echo "school is a regular file"
        fi
    else
        echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi
