#!/usr/bin/env bash
# A script to change localhost addresses

# Copy the original /etc/hosts file to ~/hosts.new
cp /etc/hosts ~/hosts.new

# Overwrite ~/hosts.new with the desired changes
echo "127.0.0.2       localhost" > ~/hosts.new
echo "8.8.8.8         facebook.com" >> ~/hosts.new

# Overwrite the original /etc/hosts with the modified ~/hosts.new
cp -f ~/hosts.new /etc/hosts
