#!/usr/bin/env bash
#Fixes a web server to run nginx as the nginx user listening to port 8080
service nginx stop
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
